
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toclevels: 1

= System Automation with Ansible and System-Roles

Ansible is an open source automation platform that uses a simple automation language
that describes an IT application infrastructure within Ansible Playbooks. Ansible is also
an automation engine that runs Ansible Playbooks.
You can utilize Ansible in many ways:

  * Device configuration management
  * Application deployment
  * Provisioning
  * Continuous delivery
  * Security and compliance
  *Orchestration

`ansible` is the primary command line tool to initiate a ad hoc command.
`ansible-playbook` is the command line tool to run Ansible Playbooks. The syntax used for configuring Ansible Playbooks is written in YAML.

The Ansible Engine product channel is provided as a convenience with the Red Hat Enterprise Linux subscription as a unsupported dependency for the implementation of RHEL System Roles. However, support of Ansible Engine product by the RHEL subscription is limited to the context of, and modules used by, RHEL System Roles. A full support subscription is available for Ansible Engine and Ansible Tower which are also able to use the RHEL System Roles.

== Ansible Concepts

There are two types of machines in the Ansible architecture: 

  * control nodes, and 
  * managed hosts
  
Ansible is installed and run from a control node.  Managed hosts are listed and organized in an *inventory*.  The *inventory* can be defined in a static text file (INI), or derived via a dynamic file determined by scripts that get the information from external sources.

By executing a *playbook* on a declared *inventory* of managed hosts, ansible runs a collection of *tasks* to transform a mananged host into a desired state.  Each *task* leverages an ansible *module* to perform the actual work and deliver a predictable and consistent outcome.  Ansible ships with hundreds of modules that perform a wide variety of actions.

Playbooks are written using a YAML markup language.

== RHEL System-Roles Concepts

Red Hat Enterprise Linux (RHEL) 7.4 introduced RHEL System Roles as a Technology Preview. The RHEL System Roles are a collection of Ansible roles and modules that provide a stable and consistent configuration interface to remotely manage RHEL 6.9 and later versions of Red Hat Enterprise Linux (including RHEL 7.5 as a Technology Preview). This effort is based on development of the Linux System Roles upstream project.

RHEL System Roles will provide the user a consistent user interface to provide settings to a given subsystem that is abstract from any one particular implementation or configuration. Thereby, making generic system configurations easy to maintain with consistent automation techniques while maintaining modularity.

The initial set of roles includes:
  * kdump
  * postfix
  * network
  * selinux
  * timesync
  
The RHEL System Roles are provided in the RHEL Extras channel.  Ansible Engine and the RHEL System Roles only need to be installed on the control node(s).  System-Roles compatibility is currently only tested against RHEL 6.9 and later clients.

== Getting Started

Starting on the host *workstation.example.com*, let's ssh over to *node1.example.com*.  No password should be required.

.[root@workstation]#
----
ssh node1.example.com
----

Verify that you are on the right host for these exercises.

.[root@node1]#
----
cheat-ansible-checkhost.sh
----

Now you are ready to begin

== Package Installation

The `rhel-system-roles` and `ansible` RPM packages are provided in the RHEL Extras channel. The Extras channel should be enabled by default in your workshop environment.

.[root@node1]#
----
yum install -y rhel-system-roles ansible
----

.Command Output
[source,indent=4]
----
..<SNIP>..
Package ansible-2.4.2.0-2.el7.noarch already installed and latest
version
Resolving Dependencies
--> Running transaction check
---> Package rhel-system-roles.noarch 0:0.6-3.el7 will be
installed
--> Finished Dependency Resolution
Installed:
rhel-system-roles.noarch 0:0.6-3.el7
..<SNIP>..
----

TIP: RHEL System Roles documentation is located in: `/usr/share/doc/rhel-system-roles/SUBSYSTEM/`

TIP: Ansible Roles documentation is located in: `/usr/share/ansible/roles/rhel-system-roles.SUBSYSTEM/`

Now that we have installed Ansible and RHEL System Roles and a general understanding of what Ansible is, let’s create and modify the initial configuration file to run a few modules against our managed hosts using our _inventory_ file.

== Configuration

=== Create and Distribute SSH Keys

Ansible is agentless.  Thus there is no additional software that needs to be installed on our clients.

Ansible does however use SSH, and so to make it convenient we need to create an SSH key on our ansible host (node1) and distribute that key to our clients (node2 & node3).

Run the following to commands to create the ssh key.  Accept the defaults and leave the passphrase empty (just hit ENTER).

.[root@node1]#
----
ssh-keygen
----

Now distribute the key to your ansible clients.  Use the root password provided to you by your instructor.

.[root@node1]#
----
ssh-copy-id node1.example.com

ssh-copy-id node2.example.com

ssh-copy-id node3.example.com
----

=== Create Configuration File

Run the following to create you ansible configuration file.

.[root@node1]#
----
cheat-ansible-config.sh
----

The previous cheat script creates the ansible configuration for the current user.  The contents are as follows:

/root/.ansible.cfg#
----
[defaults]
inventory = /root/inventory
remote_user = root
ask_pass = false
[privilege_escalation]
become = true
become_method = sudo
become_user = root
become_ask_pass = false
----

Take note of the "inventory".  This is now the default file ansible will refer to for hostnames and parameters.

=== Create Inventory File

Run the following command to create your _inventory_ file.

.[root@node1]#
----
cheat-ansible-inventory.sh
----

The previous cheat script creates the default ansible inventory for the current user.  The contents are as follows:

/root/inventory#
----
[myself]
workstation.example.com
[servers]
node2.example.com
node3.example.com
----

== AdHoc Commands

A "ansible adhoc command" typically refers to short implementation of ansible launched form the command line without formally creating a "playbook".  For example, why write a playbook to ping a collection of hosts for a quick status check.

=== Ansible AdHoc: ping

In this case "servers" refers to the collection of machines as defined in the "inventory".  And '-m' specifies the ansible module we want to execute.

.[root@node1]#
----
ansible servers -m ping
----

.Command Output
[source,indent=4]
----
node3.example.com | SUCCESS => {
"changed": false,
"ping": "pong"
}
node2.example.com | SUCCESS => {
"changed": false,
"ping": "pong"
}
----

Any time you are curious as to what the specific list of machines an ansible play will affect, try '--list-hosts'

.[root@node1]#
----
ansible servers --list-hosts
----

.Command Output
[source,indent=4]
----
hosts (2):
  node2.example.com
  node3.example.com
----

=== Ansible AdHoc: setup

The ansible "setup" module runs at the begining of each play and collects "facts" about a host.  In this example, you will specifically only collect facts about the network interface "eth0".

.[root@node1]#
----
ansible -m setup -a 'filter=ansible_eth0' node2.example.com
----

.Command Output
[source,indent=4]
----
..<SNIP>..
node2.example.com | SUCCESS => {
  "ansible_facts": {
    "ansible_eth0": {
      "active": true,
      "device": "eth0",
      "features": {
        "busy_poll": "off [fixed]",
        "fcoe_mtu": "off [fixed]",
..<SNIP>..
"ipv4": {
  "address": "10.0.0.11",
  "broadcast": "10.0.0.255",
  "netmask": "255.255.255.0",
  "network": "10.0.0.0"
  },
"ipv6": [
  {
    "address": "fe80::2ec2:60ff:fe02:d1d5",
    "prefix": "64",
    "scope": "link"
  }
----

Without specifying the "filter, the setup module will output all the facts discovered about a client.  Go ahead and try it to get an idea of how much info is available.

== Playbook with Roles

Let’s now define the role content for use with Ansible Playbooks that introduces RHEL System Roles. In this case we’ll create a role called “motd”.

First, create the directory structure for the “motd” role:

.[root@node1]#
----
cd /root
mkdir roles
cd roles
ansible-galaxy init motd
----

Second, create a jinja template file.

.[root@node1]#
----
cheat-ansible-motd-template.sh
----

Now modify the main.yml to define a variable

.[root@node1]#
----
cheat-ansible-motd-main.sh
----

And finally, adjust the playbook to call our new `motd` role.

.[root@node1]#
----
cheat-ansible-motd-playbook.sh
----

Now run the playbook with our cutom `motd` role.

.[root@node1]#
----
ansible-playbook use-motd-role.yml
----

.Command Output
[source,indent=4]
----
PLAY [Use MOTD role playbook]
*****************************************************************
TASK [Gathering Facts]
*****************************************************************
ok: [server1.example.com]
TASK [motd : Deliver MOTD file]
*****************************************************************
changed: [server1.example.com]
PLAY RECAP
*****************************************************************
server1.example.com : ok=2 changed=1 unreachable=0
failed=0
----

When the playbook was executed the tasks continued to perform because the role itself
can be identified by the roles configuration within the playbook.

=== Validation

As the user `root`, ssh to `server1.example.com` and verify that the _message of the day_ and been modified to our new standard.

.[root@node1]#
----
ssh root@server1.example.com
----

.Command Output
[source,indent=4]
----
This is the system server1.example.com.
Today's date is: 2018-05-04.
Only use this system with permission.
You can ask root@workstation.example.com for access.
----

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deplying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL7-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
