
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= System Automation with Ansible and System-Roles

Ansible is an open source automation platform that uses a simple automation language
that describes an IT application infrastructure within Ansible Playbooks. Ansible is also
an automation engine that runs Ansible Playbooks.
You can utilize Ansible in many ways:

  * Device configuration management
  * Application deployment
  * Provisioning
  * Continuous delivery
  * Security and compliance
  *Orchestration

`ansible` is the primary command line tool to initiate a ad hoc command.
`ansible-playbook` is the command line tool to run Ansible Playbooks. The syntax used for configuring Ansible Playbooks is written in YAML.

The Ansible Engine product channel is provided as a convenience with the Red Hat Enterprise Linux subscription as a unsupported dependency for the implementation of RHEL System Roles. However, support of Ansible Engine product by the RHEL subscription is limited to the context of, and modules used by, RHEL System Roles. A full support subscription is available for Ansible Engine and Ansible Tower which are also able to use the RHEL System Roles.

== Ansible Concepts








Some instrcutional text

.[root@workstation]#
----
ssh node1.example.com
----

Describe the expected output if necessary

.Command Output
[source,indent=4]
----
Output from previous command
----

== TASK 2

== TASK 3

== Additional Resources

Red Hat Documentation

    * link:https://https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_identity_management_and_access_control/deploying-session-recording[Deplying Session Recording on Red Hat Enterprise Linux]

[discrete]
== End of Unit

link:../RHEL7-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
