##
##    !! WARNING !!  Ansible only interprets 'True' and 'False'
##                   as booleans when reading ini files.  Other
##                   values such as 'true' or 'false' would be 
##                   interpreted as strings and would break various
##                   logic tests.  
##
##                   When reading YML files, booleans can take on
##                   many forms and be interpreted correctly.
##
##                   For consistency, only use unquoted booleans: True & False

all: 

  vars:

    ## ----------------------------------------
    ##    Workshop Variables

    workshop_vars:

      clustername:         "r7ovirt"
      network_basedomain:  "example.com"
      network_fqdn:        "r7ovirt.example.com"
      
      network_network:     "192.168.1.0"
      network_netmask:     "255.255.255.0"
      network_broadcast:   "192.168.1.255"
      network_prefix:      "24"
      network_gateway:     "192.168.1.1"
      network_nameserver:  "192.168.1.30"
      network_timeserver:  "192.168.1.60"
      
      set_student_password: True
      set_admin_password:   True

      ##
      ##    Passwords should be loaded from a file
      ##    or be set in credentials.yml.  Never here
      ##    unless you understand the risks.
      ##
      ##    !!! LEAVE PASSWORDS COMMENTED OUT !!!
      ##

      student_name:         "cloud-user"
      #student_password:     ""
      admin_name:           "root"
      #admin_password:       ""

    ## ----------------------------------------
    ##    Xtoph Deploy Variables

    xtoph_vars:

      deployhost_ip:       "192.168.1.170" 
      clustername:         "{{ workshop_vars.clustername }}"



## ----------------------------------------
## HOSTGROUPS & VARS
## ----------------------------------------

myDeployhost:
  hosts:
    deployer:
      h_pubIP: "{{ xtoph_vars.deployhost_ip }}"
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ workshop_vars.network_fqdn }}"
    ansible_connection: local



## -----------------

myBastion:
  hosts:
    bastion:
      h_pubIP: "192.168.1.130"
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ workshop_vars.network_fqdn }}"
    h_hwPROF:     "ovirt_sda"
    h_rsPROF:     "bastion"
    h_ksPROF:     "rhel79-bootiso"
    h_plPROF:     "ovirt"
    h_netDEV:     "eth0"
    h_blkDEV:     "sda"



## -----------------

myNodes:
  hosts:
    node1:
      h_pubIP:  "192.168.1.131"
      h_rsPROF: "tiny"
    node2:
      h_pubIP:  "192.168.1.132" 
      h_rsPROF: "tiny-extra" 
    node3:
      h_pubIP:  "192.168.1.133"
      h_rsPROF: "tiny-extra"
    node4:
      h_pubIP:  "192.168.1.134" 
      h_rsPROF: "tiny"
  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_vars.network_fqdn }}"
    h_hwPROF: "ovirt_sda"
    h_plPROF: "ovirt"
    h_ksPROF: "rhel79-bootiso"
    h_netDEV: "eth0"
    h_blkDEV: "sda"

