:gitrepo: https://github.com/xtophd/RHEL7-Workshop
:includedir: _include
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/

= RHEL7 Workshop

[discrete]
== Presented By

  * Christoph Doerbeck
  * Eddie Chen
  * Matt St. Onge
  * Joe Hackett
  * Rob Wilmoth
  
[discrete]
== Introduction

This is an effort to rebuild the RHEL 7 Workshops which I have been delivering at Red Hat Summit and to my clients on a new platform with updated docs and exercises.  This is a work in progress.

NOTE:  This whole effort is done using official Red Hat software and although things can likely be set up to work with upstream software components (Fedora, CentOS, etc...), alternate derivatives of RHEL are not tested or validated with these exercises.

[discrete]
== Conventions Used

This guide is intended to support a series of workshop exercises for individuals getting familiar with Red Hat Enterprise Linux 7.  What follows are examples of how this document is formatted and expected to be consumed.

[discrete]
=== Tips, Notes & Warnings

TIP: Extra info which could be helpful, but not essential for a given task or discussion

NOTE: Special information to pay attention

WARNING: Critical information which could help you avoid major set backs

[discrete]
=== Executing tasks on the CLI

[discrete]
==== Input

Each block of commands to execute will be labeled with the expected *user-id* and *host*.  To enhance cut & paste efficiency, the command prompt is omitted from each line.

.[root@master ~]#
----
systemctl status sshd
----

[discrete]
==== Output

Sample output will be titled with _'Your output should look like this'_ (or _'Command Output'_) and also be indented to help with visual identification.  Sometimes there will also be footnotes and/or callouts.

.Command Output
[source,indent=4]
----
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-26 12:04:16 EST; 27min ago // <1>
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 3094 (sshd)
   CGroup: /system.slice/sshd.service
           └─3094 /usr/sbin/sshd -D
...<snip>...
----
<1> This is the line we are interested in with a special note

[discrete]
==== Alternate Commands

The workshop often provides cheat-scripts to ease certain complex tasks.  This helps the class stay focused and reduces the likelihood of errors and disruptions to the workshop delivery.  Honestly, we are not here to learn `vi`, `emacs` or start debates about the merits of `sed` and `awk`.

The native commands which the cheat-scripts utilize will be documented in the following way.

.[root@master ~]#
----
cheat-service-status.sh
----

[NOTE]
====
_Native command(s) to verify system service_
----
systemctl status sshd
----
====


[discrete]
== How to Connect

There are three options to complete the lab.

  . Get the public DNS name or ip-address for 0Workstation and use ssh (or putty).
  . Connect to the Web Console on 0Workstation and use the `Terminal`
  . Get to the true console on "0WORKSTATION".  


NOTE: you will need true console (GUI) on "0WORKSTATION" for the GUI based units.

[discrete]
== RHEL 7 LAB: EXERCISES

[#toc]
  . link:{includedir}/r7-getting-started.adoc[*Workshop Preparation* - DO THIS FIRST! ]
  . link:{includedir}/r7-ansible.adoc[System Automation:  *Ansible and System Roles* ]
  . link:{includedir}/r7-systemd.adoc[Service Management: *systemd* ]
  . link:{includedir}/r7-perftune.adoc[Perfomance Analysis & Tuning: *pcp, tuned, numad* ]
  . link:{includedir}/r7-lvm.adoc[Storage Management: *lvm, ssm, vdo* ]
  . link:{includedir}/r7-nmcli.adoc[Network Management: *nmcli, bond, teamd* ]
  . link:{includedir}/r7-firewalld.adoc[Firewall Management: *firewalld* ]
  . link:{includedir}/r7-webconsole.adoc[System Management: *web console* ]
  . link:{includedir}/r7-openscap.adoc[System Security: *OpenSCAP* ]
  . link:{includedir}/r7-rear.adoc[System Backup & Restoration: *REAR* ]

////  
TO PRINT THIS DOC REMOVE THIS LINE AND COMMENTS AROUND INCLUDES
include::{includedir}/Getting-Started.adoc[leveloffset=+1]
include::{includedir}/ansible.adoc[leveloffset=+1]
////

[discrete]
== The End

Please remember to fill out the survey.  The RHEL Lab team really appreciates your time spent with us today.

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}

////
Always end files with a blank line to avoid include problems.
////
