---
- hosts: workstation.example.com
  unit_host: workstation.example.com
  unit_euid: student
  tasks:

    - name: "SETUP PERFTUNE: install packages"
      yum: name=pcp,pcp-gui,numad,numactl state=installed

    - name: "SETUP PERFTUNE: system service settings"
      yum: name=pcmd,pmlogger,numad state=stopped enabled=no

    - name: "SETUP PERFTUNE: cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-systemd-perftune.sh'}
