---
- hosts: workstation.example.com
  unit_host: workstation.example.com
  unit_euid: student
  tasks:

    - name: "SETUP PCP: install packages"
      yum: name=pcp,pcp-gui state=installed

    - name: "SETUP PCP: system service settings"
      yum: name=pcmd,pmlogger state=stopped enabled=no

    - name: "SETUP PCP: cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-systemd-pcp.sh'}
