---
- hosts: workstation.example.com
  unit_host: workstation.example.com
  unit_euid: student
  tasks:

    - name: "SETUP SYSTEMD: install packages"
      yum: name=httpd,mariadb,mariadb-server,php,php-mysql state=installed

    - name: "SETUP SYSTEMD: system service settings"
      yum: name=httpd,mariadb state=stopped enabled=no

    - name: "SETUP SYSTEMD: cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-systemd-checkhost.sh'}
