---
- hosts: node1
  tasks:

    - name: "rhel7-setup-systemd : install packages"
      yum: name=httpd,mariadb,mariadb-server,php,php-mysql state=installed

    - name: "rhel7-setup-systemd : system service settings"
      service: name="{{ item.svc }}" state=stopped enabled=no
      with_items:
        - {svc: 'mariadb'}
        - {svc: 'httpd'}

    - name: "rhel7-setup-systemd : cheat script installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0755
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-systemd-checkhost.sh'}
        - {src: 'cheat-systemd-httpdconfig.j2', dest: '/usr/local/bin/cheat-systemd-httpdconfig.sh'}
        - {src: 'cheat-systemd-mariadbconfig.j2', dest: '/usr/local/bin/cheat-systemd-mariadbconfig.sh'}
